# Generated by Django 5.2.9 on 2025-12-12 09:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StreakBonus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("streak_days", models.IntegerField()),
                ("tokens_awarded", models.IntegerField()),
                ("awarded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TokenTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("earn", "Earned"),
                            ("spend", "Spent"),
                            ("withdraw", "Withdrawn"),
                            ("bonus", "Bonus"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.IntegerField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("signup", "Signup Bonus"),
                            ("onboarding", "Completed Onboarding"),
                            ("daily_lesson", "Daily Lesson"),
                            ("daily_checkin", "Daily Check-in"),
                            ("daily_task", "Daily Task"),
                            ("weekly_quiz", "Weekly Quiz"),
                            ("streak_bonus", "Streak Bonus"),
                            ("checkup", "Prenatal Checkup"),
                            ("referral", "Referral"),
                            ("withdrawal", "Withdrawal"),
                        ],
                        max_length=30,
                    ),
                ),
                ("reference_id", models.UUIDField(blank=True, null=True)),
                ("reference_type", models.CharField(blank=True, max_length=50)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("balance_after", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
