# Generated by Django 5.2.9 on 2025-12-13 01:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("donor_name", models.CharField(blank=True, max_length=200)),
                ("donor_email", models.EmailField(blank=True, max_length=254)),
                ("donor_phone", models.CharField(blank=True, max_length=20)),
                ("is_anonymous", models.BooleanField(default=False)),
                ("amount_naira", models.DecimalField(decimal_places=2, max_digits=12)),
                ("payment_reference", models.CharField(blank=True, max_length=100)),
                (
                    "payment_method",
                    models.CharField(default="bank_transfer", max_length=50),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DonationPool",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pool_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_tokens_issued",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_tokens_withdrawn",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="tokentransaction",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="tokentransaction",
            name="balance_after",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="tokentransaction",
            name="description",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="tokentransaction",
            name="source",
            field=models.CharField(
                choices=[
                    ("signup", "Signup Bonus"),
                    ("onboarding", "Completed Onboarding"),
                    ("daily_lesson", "Daily Lesson"),
                    ("daily_checkin", "Daily Check-in"),
                    ("daily_task", "Daily Task"),
                    ("weekly_quiz", "Weekly Quiz"),
                    ("streak_bonus", "Streak Bonus"),
                    ("health_checkin", "Health Check-in"),
                    ("video_watched", "Video Watched"),
                    ("referral", "Referral"),
                    ("withdrawal", "Withdrawal"),
                    ("admin", "Admin Adjustment"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="tokentransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("earn", "Earned"),
                    ("withdraw", "Withdrawn"),
                    ("bonus", "Bonus"),
                    ("deduct", "Deducted"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="WithdrawalRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("naira_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "token_value_at_request",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                ("bank_name", models.CharField(max_length=100)),
                ("account_number", models.CharField(max_length=20)),
                ("account_name", models.CharField(max_length=200)),
                ("verification_photo", models.URLField(blank=True)),
                ("verification_notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("processing", "Processing Payment"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("payment_reference", models.CharField(blank=True, max_length=100)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_withdrawals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token_withdrawal_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
