# Generated by Django 5.2.9 on 2025-12-13 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0003_donation_donationpool_alter_tokentransaction_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="blockchain_tx",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="donation",
            name="explorer_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="tokentransaction",
            name="blockchain_tx",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="tokentransaction",
            name="explorer_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="blockchain_tx",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="explorer_url",
            field=models.URLField(blank=True),
        ),
    ]
