# Generated by Django 6.0 on 2025-12-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0003_donation_donationpool_alter_tokentransaction_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='alatpay_transaction_id',
            field=models.CharField(blank=True, help_text='ALATPay transaction ID for verification', max_length=255),
        ),
    ]
