# Generated by Django 5.2.9 on 2025-12-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0004_donation_alatpay_transaction_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="tokentransaction",
            name="blockchain_tx",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="tokentransaction",
            name="explorer_url",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
