# Generated by Django 5.2.9 on 2025-12-12 09:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyContent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("week", models.IntegerField()),
                ("day", models.IntegerField()),
                ("title", models.CharField(max_length=200)),
                ("theme", models.CharField(max_length=50)),
                ("lesson_title", models.CharField(max_length=200)),
                ("lesson_content", models.TextField()),
                ("lesson_summary", models.TextField(blank=True)),
                ("lesson_image", models.URLField(blank=True)),
                ("read_time_minutes", models.IntegerField(default=2)),
                ("tip_of_day", models.TextField()),
                ("task_title", models.CharField(max_length=200)),
                ("task_description", models.TextField()),
                ("task_type", models.CharField(max_length=50)),
                ("lesson_tokens", models.IntegerField(default=5)),
                ("checkin_tokens", models.IntegerField(default=5)),
                ("task_tokens", models.IntegerField(default=5)),
                ("total_tokens", models.IntegerField(default=15)),
                ("catchup_tokens", models.IntegerField(default=10)),
                ("is_quiz_day", models.BooleanField(default=False)),
                ("quiz_bonus_tokens", models.IntegerField(default=25)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["week", "day"],
                "unique_together": {("week", "day")},
            },
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question", models.TextField()),
                ("option_a", models.CharField(max_length=200)),
                ("option_b", models.CharField(max_length=200)),
                ("option_c", models.CharField(max_length=200)),
                ("option_d", models.CharField(max_length=200)),
                ("correct_answer", models.CharField(max_length=1)),
                ("order", models.IntegerField(default=0)),
                (
                    "daily_content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_questions",
                        to="daily_program.dailycontent",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="UserDayProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("lesson_completed", models.BooleanField(default=False)),
                ("checkin_completed", models.BooleanField(default=False)),
                ("task_completed", models.BooleanField(default=False)),
                ("quiz_completed", models.BooleanField(default=False)),
                ("is_completed", models.BooleanField(default=False)),
                ("is_catchup", models.BooleanField(default=False)),
                ("quiz_score", models.IntegerField(blank=True, null=True)),
                ("quiz_total", models.IntegerField(blank=True, null=True)),
                ("tokens_earned", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "daily_content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="daily_program.dailycontent",
                    ),
                ),
            ],
        ),
    ]
