# Generated by Django 5.2.9 on 2025-12-12 21:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily_program", "0003_add_child_and_stage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="YouTubeLesson",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("pregnancy", "Pregnancy"),
                            ("postpartum", "Postpartum"),
                            ("infant", "Infant"),
                            ("toddler", "Toddler"),
                        ],
                        default="pregnancy",
                        max_length=20,
                    ),
                ),
                ("week", models.IntegerField()),
                ("day", models.IntegerField(blank=True, null=True)),
                ("youtube_id", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("duration_seconds", models.IntegerField()),
                ("thumbnail_url", models.URLField(blank=True)),
                ("key_points", models.JSONField(default=list)),
                ("token_reward", models.IntegerField(default=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["stage", "week", "day"],
            },
        ),
        migrations.CreateModel(
            name="VideoProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("tokens_earned", models.IntegerField(default=0)),
                ("watch_time_seconds", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="daily_program.youtubelesson",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "video")},
            },
        ),
    ]
