# Generated by Django 5.2.9 on 2025-12-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyhealthlog",
            name="baby_movement",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
