# Generated by Django 5.2.9 on 2025-12-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0003_alter_dailyhealthlog_baby_movement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyhealthlog",
            name="baby_movement",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="dailyhealthlog",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
