# Generated by Django 5.2.9 on 2025-12-12 22:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("children", "0001_initial"),
        ("health", "0005_add_child_to_health"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("pregnancy_week", models.IntegerField()),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("complaint", "Symptom Complaint"),
                            ("checkin", "Daily Check-in"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "urgency_level",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("urgent", "Urgent"),
                            ("moderate", "Moderate"),
                            ("normal", "Normal"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("symptoms", models.JSONField(default=list)),
                ("ai_summary", models.TextField()),
                ("ai_assessment", models.TextField(blank=True, default="")),
                ("ai_recommendation", models.TextField(blank=True, default="")),
                ("conversation_id", models.UUIDField(blank=True, null=True)),
                ("conversation_transcript", models.TextField(blank=True, default="")),
                ("is_addressed", models.BooleanField(default=False)),
                ("addressed_at", models.DateTimeField(blank=True, null=True)),
                ("doctor_notes", models.TextField(blank=True)),
                (
                    "addressed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="addressed_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_reports",
                        to="children.child",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
