# Generated by Django 5.2.9 on 2025-12-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0006_healthreport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyhealthlog",
            name="mood",
            field=models.CharField(
                blank=True,
                choices=[
                    ("great", "Great"),
                    ("good", "Good"),
                    ("okay", "Okay"),
                    ("tired", "Tired"),
                    ("stressed", "Stressed"),
                    ("unwell", "Unwell"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
