# Generated by Django 5.2.9 on 2025-12-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="current_program_day",
        ),
        migrations.RemoveField(
            model_name="user",
            name="current_program_week",
        ),
        migrations.RemoveField(
            model_name="user",
            name="current_streak",
        ),
        migrations.RemoveField(
            model_name="user",
            name="due_date",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_first_pregnancy",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_menstrual_period",
        ),
        migrations.RemoveField(
            model_name="user",
            name="longest_streak",
        ),
        migrations.RemoveField(
            model_name="user",
            name="previous_pregnancies",
        ),
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
