# Generated by Django 5.2.9 on 2025-12-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_current_program_day_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="hospital_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="user",
            name="is_verified_doctor",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="medical_license",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="specialization",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("mother", "Mother"),
                    ("doctor", "Doctor"),
                    ("admin", "Admin"),
                ],
                default="mother",
                max_length=20,
            ),
        ),
    ]
