# Generated by Django 5.2.9 on 2025-12-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="detected_symptoms",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="parsed_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
