# Generated by Django 5.2.9 on 2025-12-12 16:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Child",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pregnant", "Pregnant"),
                            ("born", "Born"),
                            ("archived", "Archived"),
                        ],
                        default="pregnant",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("conception_date", models.DateField(blank=True, null=True)),
                ("weeks_at_registration", models.IntegerField(blank=True, null=True)),
                ("last_menstrual_period", models.DateField(blank=True, null=True)),
                ("name", models.CharField(blank=True, default="", max_length=100)),
                (
                    "nickname",
                    models.CharField(blank=True, default="Baby", max_length=50),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "birth_weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("birth_time", models.TimeField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                (
                    "delivery_type",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("current_day", models.IntegerField(default=1)),
                ("current_streak", models.IntegerField(default=0)),
                ("longest_streak", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "children",
                "ordering": ["-created_at"],
            },
        ),
    ]
