# Generated by Django 5.2.9 on 2025-12-12 16:15

import apps.passport.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("children", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PassportEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("task_completed", "Task Completed"),
                            ("lesson_completed", "Lesson Completed"),
                            ("health_checkin", "Health Check-in"),
                            ("symptom_reported", "Symptom Reported"),
                            ("ai_conversation", "AI Conversation"),
                            ("appointment", "Appointment"),
                            ("milestone", "Milestone"),
                            ("birth", "Birth"),
                            ("measurement", "Measurement"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("stage_type", models.CharField(blank=True, max_length=20)),
                ("stage_week", models.IntegerField(blank=True, null=True)),
                ("stage_day", models.IntegerField(blank=True, null=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("is_concern", models.BooleanField(default=False)),
                ("severity", models.CharField(blank=True, max_length=20)),
                ("source_type", models.CharField(blank=True, max_length=50)),
                ("source_id", models.UUIDField(blank=True, null=True)),
                ("event_date", models.DateField()),
                ("event_time", models.TimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passport_events",
                        to="children.child",
                    ),
                ),
            ],
            options={
                "ordering": ["-event_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PassportShare",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "share_code",
                    models.CharField(
                        default=apps.passport.models.generate_share_code,
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "passcode",
                    models.CharField(
                        default=apps.passport.models.generate_passcode, max_length=6
                    ),
                ),
                ("recipient_name", models.CharField(blank=True, max_length=100)),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[
                            ("doctor", "Doctor/Healthcare Provider"),
                            ("family", "Family Member"),
                            ("partner", "Partner"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "duration_type",
                    models.CharField(
                        choices=[
                            ("24h", "24 Hours"),
                            ("7d", "7 Days"),
                            ("30d", "30 Days"),
                            ("custom", "Custom"),
                        ],
                        default="7d",
                        max_length=10,
                    ),
                ),
                ("view_count", models.IntegerField(default=0)),
                ("last_viewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passport_shares",
                        to="children.child",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
