# Generated by Django 6.0 on 2025-12-12 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_email', models.EmailField(max_length=254)),
                ('amount_naira', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paystack_reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('blockchain_tx_hash', models.CharField(blank=True, help_text='Hash of blockchain recording tx', max_length=66, null=True)),
                ('blockchain_recorded', models.BooleanField(default=False)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['paystack_reference'], name='blockchain__paystac_6bc3fe_idx'), models.Index(fields=['-created_at'], name='blockchain__created_df6d03_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(db_index=True, max_length=42, unique=True)),
                ('encrypted_private_key', models.TextField(help_text='Encrypted private key - NEVER store in plain text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Wallet',
                'verbose_name_plural': 'User Wallets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TokenTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('MINT', 'Mint (Reward)'), ('BURN', 'Burn (Withdrawal)')], max_length=10)),
                ('action_type', models.CharField(choices=[('checkup', 'Health Checkup'), ('education', 'Educational Module'), ('donation', 'Platform Donation'), ('withdrawal', 'Token Withdrawal')], max_length=20)),
                ('action_id', models.CharField(help_text='Reference ID for the specific action', max_length=100)),
                ('token_amount', models.IntegerField(help_text='Amount of BLOOM tokens')),
                ('naira_equivalent', models.DecimalField(decimal_places=2, help_text='Naira value (1 BLOOM = ₦2)', max_digits=10)),
                ('tx_hash', models.CharField(db_index=True, help_text='Blockchain transaction hash', max_length=66, unique=True)),
                ('block_number', models.IntegerField(blank=True, null=True)),
                ('gas_used', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('user_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='blockchain_api.userwallet')),
            ],
            options={
                'verbose_name': 'Token Transaction',
                'verbose_name_plural': 'Token Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tx_hash'], name='blockchain__tx_hash_c32a8e_idx'), models.Index(fields=['user_wallet', '-created_at'], name='blockchain__user_wa_5a7f90_idx')],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_amount', models.IntegerField(help_text='Amount of BLOOM tokens to withdraw')),
                ('naira_amount', models.DecimalField(decimal_places=2, help_text='Naira equivalent', max_digits=10)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=100)),
                ('payment_provider', models.CharField(choices=[('OPay', 'OPay'), ('Paystack', 'Paystack'), ('Manual', 'Manual Bank Transfer')], default='OPay', max_length=50)),
                ('payment_reference', models.CharField(blank=True, help_text='Payment provider transaction reference', max_length=100, null=True)),
                ('burn_tx_hash', models.CharField(blank=True, help_text='Hash of token burn transaction', max_length=66, null=True)),
                ('burn_confirmed', models.BooleanField(default=False)),
                ('withdrawal_tx_hash', models.CharField(blank=True, help_text='Hash of withdrawal recording tx', max_length=66, null=True)),
                ('withdrawal_recorded', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Admin Approval'), ('APPROVED', 'Approved'), ('PROCESSING', 'Processing Payment'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes/rejection reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('user_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='blockchain_api.userwallet')),
            ],
            options={
                'verbose_name': 'Withdrawal Request',
                'verbose_name_plural': 'Withdrawal Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='blockchain__status_b341b3_idx'), models.Index(fields=['user_wallet', '-created_at'], name='blockchain__user_wa_a3c615_idx')],
            },
        ),
    ]
